
services:
  postgres:
    image: postgres:16
    container_name: Claims-Processor-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: claims_db
      POSTGRES_USER: claims_user
      POSTGRES_PASSWORD: claims_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claims_user -d claims_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - claims-processor-net

volumes:
  postgres_data:
    driver: local

networks:
  claims-processor-net:
    external: true
    name: claims-processor-network
